import {
  AiFillDashboard,
  AiFillProduct,
  AiOutlineBuild,
  AiOutlineInbox,
  AiOutlinePicture,
  AiOutlineRadiusSetting,
} from 'react-icons/ai'
import {
  FaRegImages,
  FaFileAlt,
  FaUsers,
  FaDatabase,
  FaList,
  FaRegFileAlt,
  FaTruck,
  FaRegCreditCard,
  FaLaptopCode,
  FaBoxes,
  FaUserEdit,
  FaUpload,
  FaImages,
  FaRegGrinStars,
  FaEye,
  FaEnvelope,
} from 'react-icons/fa'
import { FaGears, FaTicket } from 'react-icons/fa6'

export const routeMeta = [
  // ===== Dashboard =====
  {
    key: 'dashboard',
    label: 'Dashboard',
    path: '/admin',
    sidebar: true,
    icon: AiFillDashboard,
  },

  // ===== Media =====
  {
    key: 'media',
    label: 'Media',
    icon: AiOutlinePicture,
    sidebar: true,
    sidebarChildrens: ['/admin/media', '/admin/media/media-settings'],
  },
  {
    key: 'media-list',
    label: 'Media',
    path: '/admin/media',
    parent: '/admin',
    sidebar: true,
    icon: FaRegImages,
  },
  {
    key: 'media-settings',
    label: 'Media Settings',
    path: '/admin/media/media-settings',
    parent: '/admin/media',
    sidebar: true,
    icon: AiOutlineRadiusSetting,
  },
  {
    key: 'image-details',
    path: '/admin/media/detail/:_id',
    label: 'Image Details',
    parent: '/admin/media',
    sidebar: false,
    icon: FaFileAlt,
  },

  // ===== Customers =====
  {
    key: 'customers',
    path: '/admin/customers',
    label: 'Customers',
    description: 'Listing All The Customers...',
    parent: '/admin',
    sidebar: true,
    icon: FaUsers,
  },
  {
    key: 'add-customers',
    path: '/admin/customers/add',
    label: 'Add Customer',
    description: 'Add Customer...',
    parent: '/admin/customers',
    sidebar: false,
    icon: FaUsers,
  },
  {
    key: 'edit-customers',
    path: '/admin/customers/edit/:_id',
    label: 'Edit Customer',
    description: 'Edit Customer...',
    parent: '/admin/customers',
    sidebar: false,
    icon: FaUserEdit,
  },

  // ===== Catalog =====
  {
    key: 'catalog',
    label: 'Catalog',
    sidebar: true,
    icon: FaDatabase,
    sidebarChildrens: [
      '/admin/categories',
      '/admin/attributes',
      '/admin/products',
      '/admin/inventory',
      '/admin/bulk-upload',
      '/admin/reviews',
      '/admin/gold',
    ],
  },
  {
    key: 'categories',
    path: '/admin/categories',
    label: 'Categories',
    parent: '/admin',
    sidebar: true,
    icon: FaBoxes,
  },
  {
    key: 'add-categorie',
    path: '/admin/categories/add',
    label: 'Add Categorie',
    description: 'Add Categorie...',
    parent: '/admin/categories',
    sidebar: false,
    icon: FaUsers,
  },
  {
    key: 'edit-categorie',
    path: '/admin/categories/edit/:_id',
    label: 'Edit Categorie',
    description: 'Edit Categorie...',
    parent: '/admin/categories',
    sidebar: false,
    icon: FaUserEdit,
  },
  {
    key: 'attributes',
    path: '/admin/attributes',
    label: 'Product Attributes',
    parent: '/admin',
    sidebar: true,
    icon: AiOutlineBuild,
  },
  {
    key: 'products',
    path: '/admin/products',
    label: 'Products',
    parent: '/admin',
    sidebar: true,
    icon: AiFillProduct,
  },
  {
    key: 'add-products',
    path: '/admin/products/add',
    label: 'Add Products',
    description: 'Add Products...',
    parent: '/admin/products',
    sidebar: false,
    icon: FaUsers,
  },
  {
    key: 'edit-products',
    path: '/admin/products/edit/:_id',
    label: 'Edit Products',
    description: 'Edit Products...',
    parent: '/admin/products',
    sidebar: false,
    icon: FaUserEdit,
  },
  {
    key: 'inventory',
    path: '/admin/inventory',
    label: 'Inventory',
    parent: '/admin',
    sidebar: true,
    icon: AiOutlineInbox,
  },
  {
    key: 'bulk-upload',
    path: '/admin/bulk-upload',
    label: 'Bulk Upload',
    parent: '/admin',
    sidebar: true,
    icon: FaUpload,
  },
  {
    key: 'reviews',
    path: '/admin/reviews',
    label: 'Reviews',
    parent: '/admin',
    sidebar: true,
    icon: FaRegGrinStars,
  },
  {
    key: 'gold',
    path: '/admin/gold',
    label: 'Gold Price',
    parent: '/admin',
    sidebar: true,
    icon: FaRegGrinStars,
  },
  {
    key: 'add-gold',
    path: '/admin/gold/add',
    label: 'Add Gold Price',
    description: 'Add Gold Price...',
    parent: '/admin/gold',
    sidebar: false,
    icon: FaRegGrinStars,
  },
  {
    key: 'edit-gold',
    path: '/admin/gold/edit/:_id',
    label: 'Edit Gold Price',
    description: 'Edit Gold Price...',
    parent: '/admin/gold',
    sidebar: false,
    icon: FaRegGrinStars,
  },

  // ===== Contact Messages =====
  {
    key: 'contact-messages',
    path: '/admin/contact-messages',
    label: 'Contact Messages',
    parent: '/admin',
    sidebar: true,
    icon: FaEnvelope,
  },

  // ===== Orders =====
  {
    key: 'orders',
    label: 'Orders',
    sidebar: true,
    icon: FaList,
    sidebarChildrens: ['/admin/orders', '/admin/orders/order-status'],
  },
  {
    key: 'orders-list',
    path: '/admin/orders',
    label: 'Orders',
    parent: '/admin',
    sidebar: true,
    icon: FaList,
  },
  {
    key: 'order-status',
    path: '/admin/orders/order-status',
    label: 'Order Status',
    parent: '/admin/orders',
    sidebar: true,
    icon: FaList,
  },
  {
    key: 'add-order-status',
    path: '/admin/orders/order-status/add',
    label: 'Add Order Status',
    description: 'Add Order Status...',
    parent: '/admin/orders/order-status',
    sidebar: false,
    icon: FaEye,
  },
  {
    key: 'edit-order-status',
    path: '/admin/orders/order-status/edit/:_id',
    label: 'Edit Order Status',
    description: 'Edit Order Status...',
    parent: '/admin/orders/order-status',
    sidebar: false,
    icon: FaEye,
  },
  {
    key: 'edit-order',
    path: '/admin/orders/:_id',
    label: 'Edit Order',
    description: 'Edit Order...',
    parent: '/admin/orders',
    sidebar: false,
    icon: FaEye,
  },

  // ===== Reports =====
  {
    key: 'reports',
    path: '/admin/reports',
    label: 'Reports',
    parent: '/admin',
    sidebar: true,
    icon: FaRegFileAlt,
    sidebarChildrens: [
      '/admin/low-stock',
      '/admin/out-of-stock',
      '/admin/customer-reports',
      '/admin/product-liked',
      '/admin/total-purchased',
    ],
  },
  {
    key: 'low-stock',
    path: '/admin/low-stock',
    label: 'Low Stock Products',
    parent: '/admin',
    sidebar: true,
    icon: FaRegFileAlt,
  },
  {
    key: 'out-of-stock',
    path: '/admin/out-of-stock',
    label: 'Out of Stock Products',
    parent: '/admin',
    sidebar: true,
    icon: FaRegFileAlt,
  },
  {
    key: 'customer-reports',
    path: '/admin/customer-reports',
    label: 'Customer Reports',
    parent: '/admin',
    sidebar: true,
    icon: FaRegFileAlt,
  },
  {
    key: 'product-liked',
    path: '/admin/product-liked',
    label: 'Product Liked',
    parent: '/admin',
    icon: FaRegFileAlt,
  },
  {
    key: 'total-purchased',
    path: '/admin/total-purchased',
    label: 'Total Purchased',
    parent: '/admin',
    icon: FaRegFileAlt,
  },
  {
    key: 'view-customer-order-history',
    path: '/admin/customer-reports/view',
    label: 'View Customer Order History',
    parent: '/admin/customer-reports',
    icon: FaRegFileAlt,
  },

  // ===== Coupons =====
  {
    key: 'coupons',
    path: '/admin/coupons',
    label: 'Coupons',
    parent: '/admin',
    sidebar: true,
    icon: FaTicket,
  },

  // ===== Shipping =====
  {
    key: 'shipping-methods',
    path: '/admin/shipping-methods',
    label: 'Shipping Methods',
    parent: '/admin',
    sidebar: true,
    icon: FaTruck,
  },
  {
    key: 'edit-shipping-method',
    path: '/admin/shipping-methods/edit/:_id',
    label: 'Edit shipping',
    description: 'shipping Order...',
    parent: '/admin/shipping-methods',
    sidebar: false,
    icon: FaEye,
  },

  // ===== Payment =====
  {
    key: 'payment-methods',
    path: '/admin/payment-methods',
    label: 'Payment Methods',
    parent: '/admin',
    sidebar: true,
    icon: FaRegCreditCard,
  },
  {
    key: 'edit-payment-method',
    path: '/admin/payment-methods/edit/:_id',
    label: 'Edit payment',
    description: 'payment Order...',
    parent: '/admin/payment-methods',
    sidebar: false,
    icon: FaEye,
  },

  // ===== Settings =====
  {
    key: 'general-settings',
    path: '/admin/general-settings/',
    label: 'General Settings',
    parent: '/admin',
    sidebar: true,
    icon: FaGears,
    sidebarChildrens: ['/admin/general-settings'],
  },
  {
    key: 'general-settings',
    path: '/admin/general-settings',
    label: 'Store Settings',
    parent: '/admin',
    sidebar: true,
    icon: FaGears,
  },

  {
    key: 'website-settings',
    label: 'Settings (Website)',
    sidebar: true,
    parent: '/admin',
    icon: FaLaptopCode,
    sidebarChildrens: [
      '/admin/settings/website/slider-images',
      '/admin/settings/website/parallax-banners',
      '/admin/settings/website/banners',
      '/admin/settings/website/content-page',
      '/admin/settings/website/seo-content',
      '/admin/settings/website/settings',
    ],
  },
  {
    key: 'slider-images',
    path: '/admin/settings/website/slider-images',
    label: 'Slider Images',
    parent: '/admin/settings/website',
    sidebar: true,
    icon: FaRegImages,
  },

  {
    key: 'parallax-banners',
    path: '/admin/settings/website/parallax-banners',
    label: 'Parallax Banners',
    description: 'Listing The Home Banners...',
    parent: '/admin',
    sidebar: true,
    icon: FaImages,
  },

  {
    key: 'banners',
    path: '/admin/settings/website/banners',
    label: 'Banners',
    parent: '/admin/settings/website',
    sidebar: true,
    icon: FaImages,
  },

  {
    key: 'content-page',
    path: '/admin/settings/website/content-page',
    label: 'Content Pages',
    parent: '/admin/settings/website',
    sidebar: true,
    icon: FaFileAlt,
  },

  {
    key: 'seo-content',
    path: '/admin/settings/website/seo-content',
    label: 'SEO Content',
    parent: '/admin',
    sidebar: true,
    icon: FaEye,
  },

  {
    key: 'website-settings-config',
    path: '/admin/settings/website/settings',
    label: 'Website Settings',
    parent: '/admin',
    sidebar: true,
    icon: FaGears,
  },
]
