import {
  AiFillDashboard,
  AiFillProduct,
  AiOutlineBuild,
  AiOutlineInbox,
  AiOutlinePicture,
  AiOutlineRadiusSetting,
} from 'react-icons/ai'
import {
  FaRegImages,
  FaFileAlt,
  FaUsers,
  FaDatabase,
  FaList,
  FaRegFileAlt,
  FaTruck,
  FaRegCreditCard,
  FaLaptopCode,
  FaBoxes,
  FaUserEdit,
  FaUpload,
  FaRegGrinStars,
  FaEye,
} from 'react-icons/fa'
import { FaGears, FaTicket } from 'react-icons/fa6'

export const routeMeta = [
  // ===== Dashboard =====
  {
    key: 'dashboard',
    label: 'Dashboard',
    path: '/admin',
    sidebar: true,
    icon: AiFillDashboard,
  },

  // ===== Media =====
  {
    key: 'media',
    label: 'Media',
    icon: AiOutlinePicture,
    sidebar: true,
    sidebarChildrens: ['/admin/media', '/admin/media/media-settings'],
  },
  {
    key: 'media-list',
    label: 'Media',
    path: '/admin/media',
    parent: '/admin',
    sidebar: true,
    icon: FaRegImages,
  },
  {
    key: 'media-settings',
    label: 'Media Settings',
    path: '/admin/media/media-settings',
    parent: '/admin/media',
    sidebar: true,
    icon: AiOutlineRadiusSetting,
  },
  {
    key: 'image-details',
    path: '/admin/media/detail/:_id',
    label: 'Image Details',
    parent: '/admin/media',
    sidebar: false,
    icon: FaFileAlt,
  },

  // ===== Customers =====
  {
    key: 'customers',
    path: '/admin/customers',
    label: 'Customers',
    description: 'Listing All The Customers...',
    parent: '/admin',
    sidebar: true,
    icon: FaUsers,
  },
  {
    key: 'add-customers',
    path: '/admin/customers/add',
    label: 'Add Customer',
    description: 'Add Customer...',
    parent: '/admin/customers',
    sidebar: false,
    icon: FaUsers,
  },
  {
    key: 'edit-customers',
    path: '/admin/customers/edit/:_id',
    label: 'Edit Customer',
    description: 'Edit Customer...',
    parent: '/admin/customers',
    sidebar: false,
    icon: FaUserEdit,
  },

  // ===== Catalog =====
  {
    key: 'catalog',
    label: 'Catalog',
    sidebar: true,
    icon: FaDatabase,
    sidebarChildrens: [
      '/admin/categories',
      '/admin/attributes',
      '/admin/products',
      '/admin/inventory',
      '/admin/bulk-upload',
      '/admin/reviews',
    ],
  },
  {
    key: 'categories',
    path: '/admin/categories',
    label: 'Categories',
    parent: '/admin',
    sidebar: true,
    icon: FaBoxes,
  },
  {
    key: 'add-categorie',
    path: '/admin/categories/add',
    label: 'Add Categorie',
    description: 'Add Categorie...',
    parent: '/admin/categories',
    sidebar: false,
    icon: FaUsers,
  },
  {
    key: 'edit-categorie',
    path: '/admin/categories/edit/:_id',
    label: 'Edit Categorie',
    description: 'Edit Categorie...',
    parent: '/admin/categories',
    sidebar: false,
    icon: FaUserEdit,
  },
  {
    key: 'attributes',
    path: '/admin/attributes',
    label: 'Product Attributes',
    parent: '/admin',
    sidebar: true,
    icon: AiOutlineBuild,
  },
  {
    key: 'products',
    path: '/admin/products',
    label: 'Products',
    parent: '/admin',
    sidebar: true,
    icon: AiFillProduct,
  },
  {
    key: 'inventory',
    path: '/admin/inventory',
    label: 'Inventory',
    parent: '/admin',
    sidebar: true,
    icon: AiOutlineInbox,
  },
  {
    key: 'bulk-upload',
    path: '/admin/bulk-upload',
    label: 'Bulk Upload',
    parent: '/admin',
    sidebar: true,
    icon: FaUpload,
  },
  {
    key: 'reviews',
    path: '/admin/reviews',
    label: 'Reviews',
    parent: '/admin',
    sidebar: true,
    icon: FaRegGrinStars,
  },

  // ===== Orders =====
  {
    key: 'orders',
    label: 'Orders',
    sidebar: true,
    icon: FaList,
    sidebarChildrens: ['/admin/orders', '/admin/orders/order-status'],
  },
  {
    key: 'orders-list',
    path: '/admin/orders',
    label: 'Orders',
    parent: '/admin',
    sidebar: true,
    icon: FaList,
  },
  {
    key: 'order-status',
    path: '/admin/orders/order-status',
    label: 'Order Status',
    parent: '/admin/orders',
    sidebar: true,
    icon: FaList,
  },
  {
    key: 'add-order-status',
    path: '/admin/orders/order-status/add',
    label: 'Add Order Status',
    description: 'Add Order Status...',
    parent: '/admin/orders/order-status',
    sidebar: false,
    icon: FaEye,
  },
  {
    key: 'edit-order-status',
    path: '/admin/orders/order-status/edit/:_id',
    label: 'Edit Order Status',
    description: 'Edit Order Status...',
    parent: '/admin/orders/order-status',
    sidebar: false,
    icon: FaEye,
  },
  {
    key: 'edit-order',
    path: '/admin/orders/:_id',
    label: 'Edit Order',
    description: 'Edit Order...',
    parent: '/admin/orders',
    sidebar: false,
    icon: FaEye,
  },

  // ===== Reports =====
  {
    key: 'reports',
    path: '/admin/reports',
    label: 'Reports',
    parent: '/admin',
    sidebar: true,
    icon: FaRegFileAlt,
    sidebarChildrens: ['/admin/low-stock', '/admin/out-of-stock'],
  },
  {
    key: 'low-stock',
    path: '/admin/low-stock',
    label: 'Low Stock Products',
    parent: '/admin',
    sidebar: true,
    icon: FaRegFileAlt,
  },
  {
    key: 'out-of-stock',
    path: '/admin/out-of-stock',
    label: 'Out of Stock Products',
    parent: '/admin',
    sidebar: true,
    icon: FaRegFileAlt,
  },

  // ===== Coupons =====
  {
    key: 'coupons',
    path: '/admin/coupons',
    label: 'Coupons',
    parent: '/admin',
    sidebar: true,
    icon: FaTicket,
  },

  // ===== Shipping =====
  {
    key: 'shipping-methods',
    path: '/admin/shipping-methods',
    label: 'Shipping Methods',
    parent: '/admin',
    sidebar: true,
    icon: FaTruck,
  },

  // ===== Payment =====
  {
    key: 'payment-methods',
    path: '/admin/payment-methods',
    label: 'Payment Methods',
    parent: '/admin',
    sidebar: true,
    icon: FaRegCreditCard,
  },

  // ===== Settings =====
  {
    key: 'general-settings',
    path: '/admin/settings/general',
    label: 'General Settings',
    parent: '/admin',
    sidebar: true,
    icon: FaGears,
  },
  {
    key: 'website-settings',
    path: '/admin/settings/website',
    label: 'Settings (Website)',
    parent: '/admin',
    sidebar: true,
    icon: FaLaptopCode,
  },
]
